#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = waybar

exec-once = awww-daemon
exec-once = awww_set_wallpaper

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = hypridle
exec-once = udiskie
exec-once = launch_swaync

# Clipboard manager
exec-once = wl-clip-persist --clipboard regular

# Raycast-like app launcher
exec-once = vicinae server
