##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(ghostty)$,title:^(ghostty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland - suppress focus for these windows
windowrulev2 = suppressevent focus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# Remove the right-click menu blurring in Chromium browsers
windowrulev2 = noblur, class:^(.*)$, title:^(.*)$

# Remove the weird pop-up behavior in VSCode
windowrulev2 = stayfocused, class:^(codium)$
windowrulev2 = minsize 1 1, class:^(codium)$

# Make file picker windows floating
windowrulev2 = float, title:^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename), class:^(.*)$
windowrulev2 = center, title:^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename), class:^(.*)$
windowrulev2 = float, class:(xdg-desktop-portal-gtk|xdg-desktop-portal-hyprland|Xdg-desktop-portal-gtk|Xdg-desktop-portal-hyprland)
windowrulev2 = center, class:(xdg-desktop-portal-gtk|xdg-desktop-portal-hyprland|Xdg-desktop-portal-gtk|Xdg-desktop-portal-hyprland)
windowrulev2 = noborder, class:(Xdg-desktop-portal-gtk)

# Disable borders for swaync
windowrulev2 = noborder, class:(swaync)

# Make browsers opaque
#windowrule = opacity 1.0 override, class:(zen|librewolf|firefox|brave)

layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}
