# Force Audiocular Spark to use maximum resolution
pulse.properties = {
    pulse.min.req = 512/384000
    pulse.default.req = 512/384000
    pulse.min.frag = 512/384000
    pulse.default.frag = 512/384000
}

stream.properties = {
    node.latency = 512/384000
    resample.quality = 10
}
